import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BellRing, Check, CheckCircle2, ChevronRight, Clock3, Database, Edit3, Mail, Play, Send, Sparkles } from 'lucide-react';

type Props = { provider: 'Outlook' | 'Gmail'; reminders: boolean; autoDraft: boolean; replyApproval: boolean; onOpenSettings: () => void };
const titles = [
  'The client is due for a check-in',
  'The employee gets an email',
  'A ready-to-review draft is included',
  'The employee replies in the same thread',
  'The bot sends from the employee mailbox',
  'The existing system is updated',
];
const subtitles = [
  'Revin reads the last meaningful touchpoint and cadence from the existing account record.',
  'No new dashboard to remember. The reminder arrives where the employee already works.',
  'The message uses the account context and is held for human approval.',
  'Reply SEND to approve, or edit the message in your reply. The employee stays in control.',
  'After approval, the proposed workflow sends the message from the employee’s address.',
  'The activity is logged back to the current system and the next follow-up is scheduled.',
];
export default function EmailDemo({ provider, reminders, autoDraft, replyApproval, onOpenSettings }: Props) {
  const [step, setStep] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [reply, setReply] = useState<'send' | 'edit'>('send');
  const [edited, setEdited] = useState('Hi Sarah,\n\nI wanted to check in on your Q4 planning and hear how the new team structure is working out. Would a quick catch-up next week be helpful?\n\nBest,\nSaaniya');
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setStep(current => { if (current === 5) { setPlaying(false); return 5; } return current + 1; }), 3900); return () => window.clearInterval(timer); }, [playing]);
  const move = (n: number) => { setStep(Math.max(0, Math.min(5, n))); setPlaying(false); };
  return <div className="demo-page">
    <div className="demo-heading"><div><div className="eyebrow">THE EMAIL-FIRST WORKFLOW</div><h1>The follow-up happens in their inbox.</h1><p>Six scenes showing how the concept could fit on top of Revin’s existing tools.</p></div><span className="demo-stamp">INTERACTIVE CONCEPT · NO EMAILS SENT</span></div>
    {(!reminders || !autoDraft || !replyApproval) && <div className="demo-settings-note">One or more assistant settings are off. This storyboard shows the complete workflow with all settings enabled. <button onClick={onOpenSettings}>Review settings <ArrowRight size={14}/></button></div>}<div className="demo-flowline"><span><Database size={17}/> Existing CRM</span><ChevronRight size={16}/><span><BellRing size={17}/> Revin assistant</span><ChevronRight size={16}/><span><Mail size={17}/> {provider} inbox</span><ChevronRight size={16}/><span><CheckCircle2 size={17}/> Client touchpoint</span></div>
    <div className="demo-stage"><div className="demo-stage-head"><div><span className="demo-kicker">SCENE {String(step + 1).padStart(2,'0')} / 06</span><h2>{titles[step]}</h2><p>{subtitles[step]}</p></div><button className="demo-play" onClick={() => { if (step === 5) setStep(0); setPlaying(true); }}><Play size={16} fill="currentColor"/> {playing ? 'Playing' : step === 5 ? 'Replay' : 'Play all'}</button></div>
      <div className="demo-canvas" key={`${step}-${reply}`}>
        {step === 0 && <div className="scene scene-record"><div className="scene-overline">EXISTING SYSTEM OF RECORD</div><div className="mock-crm"><div className="mock-top"><span className="mock-logo">R</span><span>Accounts / Northstar Mechanical</span><span className="mock-tag">CRM · SIMULATED</span></div><div className="mock-body"><span className="mock-avatar">NM</span><div><small>ACTIVE CLIENT</small><h3>Northstar Mechanical</h3><p>Owner: Saaniya Makandar · Contact: Sarah Chen</p></div></div><div className="mock-details"><div><small>LAST MEANINGFUL CONTACT</small><strong>68 days ago</strong></div><div><small>FOLLOW-UP CADENCE</small><strong>Every 60 days</strong></div><div><small>NEXT ACTION</small><strong className="alert">8 days overdue</strong></div></div></div><div className="floating-detection"><Clock3 size={19}/><span>Follow-up due detected</span><strong>→</strong></div></div>}
        {step === 1 && <div className="scene scene-inbox"><div className="mail-window"><MailHeader provider={provider}/><div className="mail-inbox-title">Inbox <span>1 new</span></div><div className="mail-list"><div className="mail-list-item highlight"><span className="mail-unread"/><strong>Revin Follow-Up Assistant</strong><span>Northstar Mechanical needs a check-in</span><small>9:02 AM</small></div><div className="mail-list-item"><span/><strong>Operations team</strong><span>Monday planning notes</span><small>Yesterday</small></div><div className="mail-list-item"><span/><strong>Sarah Chen</strong><span>Re: Q4 account planning</span><small>Sep 12</small></div></div></div><div className="floating-mail"><BellRing size={17}/> Reminder delivered to Saaniya’s inbox</div></div>}
        {step === 2 && <div className="scene scene-message"><div className="mail-window message-window"><MailHeader provider={provider}/><div className="message-subject">Northstar Mechanical is ready for a check-in <span>Inbox</span></div><div className="message-from"><span className="bot-avatar">R</span><div><strong>Revin Follow-Up Assistant</strong><small>to Saaniya · 9:02 AM</small></div></div><div className="message-content"><p>Hi Saaniya,</p><p>It’s been 68 days since your last meaningful contact with <strong>Northstar Mechanical</strong>. Your target is every 60 days.</p><div className="embedded-draft"><span><Sparkles size={14}/> SUGGESTED CLIENT EMAIL</span><p>Hi Sarah,</p><p>I wanted to check in on your Q4 planning and hear how the new team structure is working out. Would a quick catch-up next week be helpful?</p><p>Best,<br/>Saaniya</p></div><div className="reply-instruction">Reply <b>SEND</b> to approve, or reply with your edited version.</div></div></div></div>}
        {step === 3 && <div className="scene scene-reply"><div className="mail-window message-window"><MailHeader provider={provider}/><div className="message-subject">Re: Northstar Mechanical is ready for a check-in</div><div className="reply-toggle"><button className={reply === 'send' ? 'active' : ''} onClick={() => setReply('send')}><Check size={15}/> Reply SEND</button><button className={reply === 'edit' ? 'active' : ''} onClick={() => setReply('edit')}><Edit3 size={15}/> Edit and reply</button></div><div className="compose-reply"><div className="compose-to">To: Revin Follow-Up Assistant</div>{reply === 'send' ? <div className="compose-body"><b>SEND</b><span>The bot will use the reviewed draft shown above.</span></div> : <textarea aria-label="Edited reply" value={edited} onChange={e => setEdited(e.target.value)}/>}<div className="compose-footer"><span>Reply stays inside {provider}</span><span className="fake-send"><Send size={14}/> Reply to assistant</span></div></div></div></div>}
        {step === 4 && <div className="scene scene-sent"><div className="mail-window message-window"><MailHeader provider={provider}/><div className="message-subject">Sent: Checking in with Northstar Mechanical <span>Sent items</span></div><div className="message-from"><span className="person-mail-avatar">SM</span><div><strong>Saaniya Makandar</strong><small>to Sarah Chen · 9:04 AM</small></div><span className="sent-check"><CheckCircle2 size={16}/> SENT · SIMULATED</span></div><div className="message-content"><p>Hi Sarah,</p><p>{reply === 'edit' ? edited.split('\n').filter(Boolean).slice(1,-2).join(' ') : 'I wanted to check in on your Q4 planning and hear how the new team structure is working out. Would a quick catch-up next week be helpful?'}</p><p>Best,<br/>Saaniya</p></div></div><div className="send-route"><span>Revin assistant</span><ArrowRight size={19}/><span>Saaniya’s {provider}</span><ArrowRight size={19}/><span>Sarah Chen</span></div></div>}
        {step === 5 && <div className="scene scene-complete"><div className="complete-icon"><Check size={29}/></div><div className="scene-overline">LOOP CLOSED</div><h3>Relationship back on track.</h3><p>The proposed workflow logs the approved email in the existing account record, resets the cadence, and gives the team visibility without another daily dashboard habit.</p><div className="complete-stats"><span><CheckCircle2 size={17}/> Contact logged</span><span><Clock3 size={17}/> Next check-in: 60 days</span><span><Database size={17}/> CRM updated</span></div><button onClick={onOpenSettings}>See reminder settings <ArrowRight size={16}/></button></div>}
      </div>
      <div className="demo-controls"><button className="demo-arrow" onClick={() => move(step-1)} disabled={step === 0} aria-label="Previous scene"><ArrowLeft size={19}/></button><div className="demo-dots">{titles.map((title,i) => <button key={title} className={i === step ? 'active' : ''} onClick={() => move(i)} aria-label={`Scene ${i+1}: ${title}`}>{i === step && <span>{String(i+1).padStart(2,'0')} · {title}</span>}</button>)}</div><button className="demo-arrow" onClick={() => move(step+1)} disabled={step === 5} aria-label="Next scene"><ArrowRight size={19}/></button></div>
    </div>
    <div className="demo-disclaimer"><Sparkles size={18}/><span>This is a simulated product vision using fictional accounts and mailbox screens. Live CRM sync, mailbox delivery, reply parsing, and sending would require approved integrations and implementation.</span></div>
  </div>;
}
function MailHeader({ provider }: { provider: string }) { return <div className="mail-window-head"><span className="mail-provider"><Mail size={15}/> {provider}</span><span>Search mail</span><span className="mail-user">SM</span></div>; }
